const { _electron: electron } = require('playwright');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const data = await fs.mkdtemp(path.join(os.tmpdir(), 'r1ft-ui-'));
  let app;
  try {
    app = await electron.launch({ args: [path.join(__dirname, '..')], env: { ...process.env, ELECTRON_RUN_AS_NODE: undefined, R1FT_TEST_DATA: data }, timeout: 30000 });
    const page = await app.firstWindow();
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.getByRole('heading', { name: 'Let’s play.' }).waitFor();
    await fs.mkdir(path.join(__dirname, '../.test-output'), { recursive: true });
    await page.screenshot({ path: path.join(__dirname, '../.test-output/home.png') });
    await page.getByRole('button', { name: 'Accounts', exact: true }).click();
    await page.getByPlaceholder('Minecraft username').fill('ViperTester');
    await page.getByRole('button', { name: 'Add account', exact: true }).click();
    await page.getByRole('heading', { name: 'ViperTester', exact: true }).waitFor();
    const stored = JSON.parse(await fs.readFile(path.join(data, 'launcher.json'), 'utf8'));
    assert.equal(stored.accounts[0].name, 'ViperTester');
    const publicState = await page.evaluate(() => window.launcher.state());
    assert.equal(publicState.accounts[0].type, 'offline');
    assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
    await page.getByRole('button', { name: 'Home', exact: true }).click();
    await page.getByRole('button', { name: 'Local closet' }).click();
    await page.getByRole('heading', { name: 'Local closet' }).waitFor();
    await page.getByRole('button', { name: 'Close dialog' }).click();
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    await page.getByRole('heading', { name: 'Launcher settings' }).waitFor();
    await page.locator('#snapshots').check();
    await page.getByRole('button', { name: 'Save settings' }).click();
    await page.waitForFunction(async () => (await window.launcher.state()).settings.snapshots);
    await page.getByRole('button', { name: 'Home', exact: true }).click();
    await page.getByRole('button', { name: 'Create game', exact: true }).click();
    await page.locator('#create-version option[value="1.21.1"]').waitFor({ state: 'attached', timeout: 90000 });
    await page.locator('#create-name').fill('UI Test World');
    await page.locator('#create-version').selectOption('1.21.1');
    await page.getByRole('dialog').getByRole('button', { name: 'Create game', exact: true }).click();
    await page.getByRole('heading', { name: 'UI Test World', exact: true }).waitFor({ timeout: 90000 });
    await page.getByRole('heading', { name: 'Mods', exact: true }).waitFor();
    await page.screenshot({ path: path.join(__dirname, '../.test-output/instance.png') });
    await page.getByRole('button', { name: 'Discover modpacks', exact: true }).click();
    await page.locator('.project-card').first().waitFor({ timeout: 90000 });
    await page.screenshot({ path: path.join(__dirname, '../.test-output/modrinth.png') });
    await page.locator('.project-card').first().click();
    await page.locator('#install-version').waitFor({ timeout: 90000 });
    assert.ok(await page.locator('#install-version option').count());
    await page.getByRole('button', { name: 'Close dialog' }).click();
    assert.deepEqual(errors, []);
    console.log('PASS: Electron boot, isolated renderer, offline account persistence, skin closet, settings, instance creation, live Modrinth search and version dialog.');
  } finally { await app?.close(); await fs.rm(data, { recursive: true, force: true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
